package jp.tsubakicraft.tradeshift.domain.enums;

public enum DocState {
    ACCEPTED, REJECTED_BY_RECEIVER, DELIVERED, OVERDUE, PAID_CONFIRMED, PAID_UNCONFIRMED, REJECTED_BY_SENDER, DISPUTED_BY_RECEIVER, FAILED_DELIVERY, PENDING_NOT_A_CONTACT
}
